name: tinynerf
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - plotly
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - contourpy=1.0.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.15
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.0.11
  - pcre=8.45
  - pip=23.3
  - plotly=5.18.0
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.10.13
  - python-dateutil=2.8.2
  - qt-main=5.15.2
  - readline=8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - black==23.10.1
      - bleach==6.1.0
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - comm==0.1.4
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fastjsonschema==2.18.1
      - filelock==3.9.0
      - fqdn==1.5.1
      - fsspec==2023.4.0
      - idna==3.4
      - ipykernel==6.26.0
      - ipython==8.17.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.5.0
      - jupyter-core==5.5.0
      - jupyter-events==0.8.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.9.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - markupsafe==2.1.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.10.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.0
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.24.1
      - overrides==7.4.0
      - packaging==23.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.2
      - pexpect==4.8.0
      - pillow==10.1.0
      - platformdirs==3.11.0
      - prometheus-client==0.18.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.16.1
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.6
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - terminado==0.17.1
      - tinycss2==1.2.1
      - torch==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - traitlets==5.13.0
      - triton==2.1.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.4.0
      - uri-template==1.3.0
      - urllib3==1.26.13
      - wcwidth==0.2.9
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
